FORMAT: 1A
HOST: http://sweetmusic.me/

# SweetMusic
Simple API for retrieving information regarding Artists, Albums and Tracks

# Group Search

## Search All Tables [/search/all{?searchterm}]
<code>/search/all?searchterm={terms}</code><br>

#### Parameters
- <code>searchterm</code> *(string, required)* - terms to search the database

+ Parameters
    + searchterm: Kanye (string) - terms to search the database

### GET Search All Tables [GET]
+ Response 200

        {
            "and": {
                "albums": [
                  {
                    "id": "1j2x7FJXTgUT0X5hZ8TDXE",
                    "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                    "name": "Dark Sky Paradise"
                  },
                  ...
                ],
                "artists": [
                  {
                    "id": "5K4W6rqBFWDnAN6FQUkS6x",
                    "img": "https://i.scdn.co/image/a2fe02386dcb76d7ecda994db995c3fb12694690",
                    "name": "Kanye West"
                  }
                ],
                "tracks": [
                  {
                    "id": "30CZcZ0NpTXjVJJa5X5nwf",
                    "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                    "name": "All Your Fault"
                  },
                  ...
                ]
            },
            "or": {
                         "Kanye": {
                  "albums": [
                    {
                      "id": "1j2x7FJXTgUT0X5hZ8TDXE",
                      "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                      "name": "Dark Sky Paradise"
                    },
                    ...
                  ],
                  "artists": [
                    {
                      "id": "5K4W6rqBFWDnAN6FQUkS6x",
                      "img": "https://i.scdn.co/image/a2fe02386dcb76d7ecda994db995c3fb12694690",
                      "name": "Kanye West"
                    }
                  ],
                  "tracks": [
                    {
                      "id": "30CZcZ0NpTXjVJJa5X5nwf",
                      "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                      "name": "All Your Fault"
                    },
                    ...
                  ]
            }
        }

## Search Artists [/search/artists{?searchterm}]
<code>/search/artists?searchterm={terms}</code><br>

#### Parameters
- <code>searchterm</code> *(string, required)* - terms to search the database

+ Parameters
    + searchterm: Kanye (string) - terms to search the database


### GET Search Artists [GET]
+ Response 200

        {
            "and": {
                "albums": [
                  {
                    "id": "1j2x7FJXTgUT0X5hZ8TDXE",
                    "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                    "name": "Dark Sky Paradise"
                  },
                  ...
                ],
                "artists": [
                  {
                    "id": "5K4W6rqBFWDnAN6FQUkS6x",
                    "img": "https://i.scdn.co/image/a2fe02386dcb76d7ecda994db995c3fb12694690",
                    "name": "Kanye West"
                  }
                ],
                "tracks": [
                  {
                    "id": "30CZcZ0NpTXjVJJa5X5nwf",
                    "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                    "name": "All Your Fault"
                  },
                  ...
                ]
            },
            "or": {
                         "Kanye": {
                  "albums": [
                    {
                      "id": "1j2x7FJXTgUT0X5hZ8TDXE",
                      "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                      "name": "Dark Sky Paradise"
                    },
                    ...
                  ],
                  "artists": [
                    {
                      "id": "5K4W6rqBFWDnAN6FQUkS6x",
                      "img": "https://i.scdn.co/image/a2fe02386dcb76d7ecda994db995c3fb12694690",
                      "name": "Kanye West"
                    }
                  ],
                  "tracks": [
                    {
                      "id": "30CZcZ0NpTXjVJJa5X5nwf",
                      "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                      "name": "All Your Fault"
                    },
                    ...
                  ]
            }
        }

## Search Albums [/search/albums{?searchterm}]
<code>/search/albums?searchterm={terms}</code><br>

#### Parameters
- <code>searchterm</code> *(string, required)* - terms to search the database

+ Parameters
    + searchterm: Kanye (string) - terms to search the database

### GET Search Albums [GET]
+ Response 200

        {
            "and": {
                "albums": [
                  {
                    "id": "1j2x7FJXTgUT0X5hZ8TDXE",
                    "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                    "name": "Dark Sky Paradise"
                  },
                  ...
                ],
                "artists": [
                  {
                    "id": "5K4W6rqBFWDnAN6FQUkS6x",
                    "img": "https://i.scdn.co/image/a2fe02386dcb76d7ecda994db995c3fb12694690",
                    "name": "Kanye West"
                  }
                ],
                "tracks": [
                  {
                    "id": "30CZcZ0NpTXjVJJa5X5nwf",
                    "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                    "name": "All Your Fault"
                  },
                  ...
                ]
            },
            "or": {
                         "Kanye": {
                  "albums": [
                    {
                      "id": "1j2x7FJXTgUT0X5hZ8TDXE",
                      "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                      "name": "Dark Sky Paradise"
                    },
                    ...
                  ],
                  "artists": [
                    {
                      "id": "5K4W6rqBFWDnAN6FQUkS6x",
                      "img": "https://i.scdn.co/image/a2fe02386dcb76d7ecda994db995c3fb12694690",
                      "name": "Kanye West"
                    }
                  ],
                  "tracks": [
                    {
                      "id": "30CZcZ0NpTXjVJJa5X5nwf",
                      "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                      "name": "All Your Fault"
                    },
                    ...
                  ]
            }
        }

## Search Tracks [/search/tracks{?searchterm}]
<code>/search/tracks?searchterm={terms}</code><br>

#### Parameters
- <code>searchterm</code> *(string, required)* - terms to search the database

+ Parameters
    + searchterm: Kanye (string) - terms to search the database

### GET Search Tracks [GET]
+ Response 200

        {
            "and": {
                "albums": [
                  {
                    "id": "1j2x7FJXTgUT0X5hZ8TDXE",
                    "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                    "name": "Dark Sky Paradise"
                  },
                  ...
                ],
                "artists": [
                  {
                    "id": "5K4W6rqBFWDnAN6FQUkS6x",
                    "img": "https://i.scdn.co/image/a2fe02386dcb76d7ecda994db995c3fb12694690",
                    "name": "Kanye West"
                  }
                ],
                "tracks": [
                  {
                    "id": "30CZcZ0NpTXjVJJa5X5nwf",
                    "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                    "name": "All Your Fault"
                  },
                  ...
                ]
            },
            "or": {
                         "Kanye": {
                  "albums": [
                    {
                      "id": "1j2x7FJXTgUT0X5hZ8TDXE",
                      "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                      "name": "Dark Sky Paradise"
                    },
                    ...
                  ],
                  "artists": [
                    {
                      "id": "5K4W6rqBFWDnAN6FQUkS6x",
                      "img": "https://i.scdn.co/image/a2fe02386dcb76d7ecda994db995c3fb12694690",
                      "name": "Kanye West"
                    }
                  ],
                  "tracks": [
                    {
                      "id": "30CZcZ0NpTXjVJJa5X5nwf",
                      "img": "https://i.scdn.co/image/dc3b00d6525ae23335f64768436002bd1bb8863b",
                      "name": "All Your Fault"
                    },
                    ...
                  ]
            }
        }

# Group Artists
## Arbitrary Artists [/artists/{page_num}{?psize,sort,order}]
<code>/artists/{page_num}?psize={psize}&sort={col_attr}&order={asc_desc}</code><br>
Request an arbitrary list of albums. You can specify the number of artists returned, using the page and optional psize as offset. <br>
Optionally you can set to sort by a specific column attribute and determine if the order is ascending or descending.
#### Parameters
- <code>page_num</code> *(number, required)* - used as an offset to query by page
- <code>psize</code> *(number, optional)* - used to specify the size of the list
- <code>col_attr</code> *(string, optional)* - takes a specific column to sort the list of artists by
- <code>asc_desc</code> *(string, optional)* - default ascending sort order when sort is set, can set to descending with 'desc'

#### Sort options
- <code>artist_name</code>
- <code>num_albums</code>
- <code>recent_album</code>
- <code>top_track</code>
- <code>popularity</code>

+ Parameters
    + page_num: 1 (number) - indicates the offset or page
    + psize: 3 (number, optional) - indicates the number of artists per page
    + sort: popularity (string, optional) - give it a column attribute to sort by
    + order: desc (string, optional) - default is ascending when sort is set, can set to descending order with 'desc'

### GET Arbritrary Artists [GET]
+ Response 200 (application/json)
    + Attributes (object)
        + col_img: {"url": "https://i.scdn.co/image/295f7e4e9cb73f559bbc14ee42097faaade17170"} (object) - list of img hrefs for the artist
        + db_id: 1 (number) - database id
        + id: 26T3LtbuGT1Fu9m0eRq5X3 (string) - spotify id for the artist
        + name: Cage the Elephant (string) - name of the artist
        + num_albums: 20 (number) - number of albums the artist has
        + popularity: 76 (number) - popularity index of artist according to spotify
        + recent_album: Tell Me I'm Pretty (string) - name of the most recent album
        + spotify_uri: spotify:artist:26T3LtbuGT1Fu9m0eRq5X3 (string) - uri for spotify for the artist
        + top_track: Ain't No Rest for the Wicked (string) - name of their top track
                
    + Body
    
            {
              "artists": [
                {
                  "col_img": {
                    "url": "https://i.scdn.co/image/295f7e4e9cb73f559bbc14ee42097faaade17170"
                  },
                  "db_id": 1,
                  "id": "26T3LtbuGT1Fu9m0eRq5X3",
                  "name": "Cage The Elephant",
                  "num_albums": 20,
                  "popularity": 76,
                  "recent_album": "Tell Me I'm Pretty",
                  "spotify_uri": "spotify:artist:26T3LtbuGT1Fu9m0eRq5X3",
                  "top_track": "Ain't No Rest for the Wicked"
                },
                {
                  "col_img": {
                    "url": "https://i.scdn.co/image/cbbdfb209cc38b2999b1882f42ee642555316313"
                  },
                  "db_id": 2,
                  "id": "4dpARuHxo51G3z768sgnrY",
                  "name": "Adele",
                  "num_albums": 20,
                  "popularity": 91,
                  "recent_album": "21",
                  "spotify_uri": "spotify:artist:4dpARuHxo51G3z768sgnrY",
                  "top_track": "Hello"
                },
                {
                  "col_img": {
                    "url": "https://i.scdn.co/image/f4c6df387feebef2c94bde6117c38dd8dab69533"
                  },
                  "db_id": 3,
                  "id": "25u4wHJWxCA9vO0CzxAbK7",
                  "name": "Lukas Graham",
                  "num_albums": 20,
                  "popularity": 89,
                  "recent_album": "Lukas Graham (Blue Album)",
                  "spotify_uri": "spotify:artist:25u4wHJWxCA9vO0CzxAbK7",
                  "top_track": "7 Years"
                }
              ],
              "page": 1,
              "psize": 3,
              "total_artists": 124
            }

## Specific Artists [/artists{?ids}]
<code>/artists?ids={artists_ids}</code><br>
Request all information regarding specific artists related to **ids**
#### Parameters
- <code>artist_ids</code> *(string, required)* - comma separated list of spotify ids


+ Parameters
    + ids: 25u4wHJWxCA9vO0CzxAbK7 (string, required) - comma separated list of spotify ids

### GET Specific Artists [GET]
+ Response 200 (application/json)
    + Attributes (object)
        + col_img: {"url": "https://i.scdn.co/image/f4c6df387feebef2c94bde6117c38dd8dab69533"} (object) - list of img hrefs for the artist
        + db_id: 3 (number) - database id
        + id: 25u4wHJWxCA9vO0CzxAbK7 (string) - spotify id for the artist
        + name: Lukas Graham (string) - name of the artist
        + num_albums: 20 (number) - number of albums the artist has
        + popularity: 89 (number) - popularity index of artist according to spotify
        + recent_album: Lukas Graham Blue Album (string) - name of the most recent album
        + spotify_uri: spotify:artist:25u4wHJWxCA9vO0CzxAbK7 (string) - uri for spotify for the artist
        + top_track: 7 Years (string) - name of their top track

    + Body
    
            {
              "artists": [
                {
                  "col_img": {
                    "url": "https://i.scdn.co/image/f4c6df387feebef2c94bde6117c38dd8dab69533"
                  },
                  "db_id": 3,
                  "id": "25u4wHJWxCA9vO0CzxAbK7",
                  "name": "Lukas Graham",
                  "num_albums": 20,
                  "popularity": 89,
                  "recent_album": "Lukas Graham (Blue Album)",
                  "spotify_uri": "spotify:artist:25u4wHJWxCA9vO0CzxAbK7",
                  "top_track": "7 Years"
                }
              ]
            }

# Group Albums
## Arbitrary Albums [/albums/{page_num}{?psize,sort,order}]
<code>/albums/{page_num}?psize={psize}&sort={col_attr}&order={asc_desc}</code><br>
Request an arbitrary list of albums. You can specify the number of albums returned, using the page and optional psize as offset. <br>
Optionally you can set to sort by a specific column attribute and determine if the order is ascending or descending.

#### Parameters
- <code>page_num</code> *(number, required)* - used as an offset to query by page
- <code>psize</code> *(number, optional)* - used to specify the size of the list
- <code>col_attr</code> *(string, optional)* - takes a specific column to sort the list of albums by
- <code>asc_desc</code> *(string, optional)* - default ascending sort order if sort is set, can set to descending with 'desc'

#### Sort options
- <code>album_name</code>
- <code>artist_name</code>
- <code>release_date</code>
- <code>num_tracks</code>
- <code>length</code>

+ Parameters
    + page_num: 1 (number) - indicates the offset or page
    + psize: 3 (number, optional) - indicates the number of albums per page
    + sort: album_name (string, optional) - takes a specific column to sort the list of albums by
    + order: desc (string, optional) - default ascending sort order if sort is set, can set to descending with 'desc'

### Get Albums [GET]
+ Response 200 (application/json)

    + Attributes
        + artist_name: Cage The Elephant (string, required) - name of the artists
        + artists: [] (array, required) - array of artists and their information
        + col_img: {"url": "https://i.scdn.co/image/295f7e4e9cb73f559bbc14ee42097faaade17170"} (object, required) - contains url for img of album
        + db_id: 1 (number, required) - id in database
        + images: "https://i.scdn.co/image/a13016817c0496ee44a48adc80b5c345e8c8925e" (string, optional) - another way to find an image of the album
        + length: "38:17" (string, required) - total length of the album formatted in minutes and seconds
        + name: "Tell Me I'm Pretty" (string, required) - name of the album
        + num_tracks: 10 (number, required) - number of tracks in the album
        + release_date: `2015-12-18` (string, required) - date the album was released
        + spotify_uri: spotify:album:0nW0w37lrQ87k7PLZvC4qJ (string, required) - uri to find this artist on spotify
        + tracks: [] (array, required) - array of tracks on the album
        
    + Body
    
            {
              "albums": [
                {
                  "artist_name": "Cage The Elephant",
                  "artists": [
                    {
                      "col_img": {
                        "url": "https://i.scdn.co/image/295f7e4e9cb73f559bbc14ee42097faaade17170"
                      },
                      "db_id": 1,
                      "id": "26T3LtbuGT1Fu9m0eRq5X3",
                      "name": "Cage The Elephant",
                      "num_albums": 20,
                      "popularity": 76,
                      "recent_album": "Tell Me I'm Pretty",
                      "spotify_uri": "spotify:artist:26T3LtbuGT1Fu9m0eRq5X3",
                      "top_track": "Ain't No Rest for the Wicked"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/d1b4e53b2f815ab43fb140c439d0dcae27c16e8a"
                  },
                  "db_id": 1,
                  "id": "0nW0w37lrQ87k7PLZvC4qJ",
                  "images": "https://i.scdn.co/image/a13016817c0496ee44a48adc80b5c345e8c8925e",
                  "length": "38:17",
                  "name": "Tell Me I'm Pretty",
                  "num_tracks": 10,
                  "release_date": "2015-12-18",
                  "spotify_uri": "spotify:album:0nW0w37lrQ87k7PLZvC4qJ",
                  "tracks": [
                    {
                      "album": "Tell Me I'm Pretty",
                      "album_cover_url": "https://i.scdn.co/image/a13016817c0496ee44a48adc80b5c345e8c8925e",
                      "album_name": "Tell Me I'm Pretty",
                      "artist_name": "Cage The Elephant",
                      "artists": [
                        {
                          "artist_id": "26T3LtbuGT1Fu9m0eRq5X3",
                          "artist_name": "Cage The Elephant"
                        }
                      ]
                  ]
                },
                {
                  "artist_name": "Adele",
                  "artists": [
                    {
                      "col_img": {
                        "url": "https://i.scdn.co/image/cbbdfb209cc38b2999b1882f42ee642555316313"
                      },
                      "db_id": 2,
                      "id": "4dpARuHxo51G3z768sgnrY",
                      "name": "Adele",
                      "num_albums": 20,
                      "popularity": 91,
                      "recent_album": "21",
                      "spotify_uri": "spotify:artist:4dpARuHxo51G3z768sgnrY",
                      "top_track": "Hello"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/9cc65b0596960faa44a0328af13048573eefecb8"
                  },
                  "db_id": 2,
                  "id": "1azUkThwd2HfUDdeNeT147",
                  "images": "https://i.scdn.co/image/4e370e394e5b5ae0c4ab07fc0dcff31239c3da9c",
                  "length": "48:00",
                  "name": "21",
                  "num_tracks": 11,
                  "release_date": "2011-01-19",
                  "spotify_uri": "spotify:album:1azUkThwd2HfUDdeNeT147",
                  "tracks": [
                    {
                      "album": "21",
                      "album_cover_url": "https://i.scdn.co/image/4e370e394e5b5ae0c4ab07fc0dcff31239c3da9c",
                      "album_name": "21",
                      "artist_name": "Adele",
                      "artists": [
                        {
                          "artist_id": "4dpARuHxo51G3z768sgnrY",
                          "artist_name": "Adele"
                        }
                      ],
                      "col_img": {
                        "url": "https://i.scdn.co/image/9cc65b0596960faa44a0328af13048573eefecb8"
                      },
                      "db_id": 20,
                      "duration": "3:48",
                      "duration_ms": 228293,
                      "id": "1CkvWZme3pRgbzaxZnTl5X",
                      "name": "Rolling in the Deep",
                      "release_date": "2011-01-19",
                      "spotify_id": "1CkvWZme3pRgbzaxZnTl5X",
                      "spotify_uri": "spotify:track:1CkvWZme3pRgbzaxZnTl5X"
                    }
                  ]
                },
                {
                  "artist_name": "Lukas Graham",
                  "artists": [
                    {
                      "col_img": {
                        "url": "https://i.scdn.co/image/f4c6df387feebef2c94bde6117c38dd8dab69533"
                      },
                      "db_id": 3,
                      "id": "25u4wHJWxCA9vO0CzxAbK7",
                      "name": "Lukas Graham",
                      "num_albums": 20,
                      "popularity": 89,
                      "recent_album": "Lukas Graham (Blue Album)",
                      "spotify_uri": "spotify:artist:25u4wHJWxCA9vO0CzxAbK7",
                      "top_track": "7 Years"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/9df24b14adba7b4d9fd7de164390cca6bd97f9c8"
                  },
                  "db_id": 3,
                  "id": "7kFmBZLF39JWv1OIRzWDkp",
                  "images": "https://i.scdn.co/image/c5c91131c1725d05f4f26b3113799840c0de9255",
                  "length": "46:02",
                  "name": "Lukas Graham (Blue Album)",
                  "num_tracks": 14,
                  "release_date": "2015-10-30",
                  "spotify_uri": "spotify:album:7kFmBZLF39JWv1OIRzWDkp",
                  "tracks": [
                    {
                      "album": "Lukas Graham (Blue Album)",
                      "album_cover_url": "https://i.scdn.co/image/c5c91131c1725d05f4f26b3113799840c0de9255",
                      "album_name": "Lukas Graham (Blue Album)",
                      "artist_name": "Lukas Graham",
                      "artists": [
                        {
                          "artist_id": "25u4wHJWxCA9vO0CzxAbK7",
                          "artist_name": "Lukas Graham"
                        }
                      ],
                      "col_img": {
                        "url": "https://i.scdn.co/image/9df24b14adba7b4d9fd7de164390cca6bd97f9c8"
                      },
                      "db_id": 31,
                      "duration": "3:57",
                      "duration_ms": 237300,
                      "id": "4dbV37qzkwZOnkGVpsR0Q7",
                      "name": "7 Years",
                      "release_date": "2015-10-30",
                      "spotify_id": "4dbV37qzkwZOnkGVpsR0Q7",
                      "spotify_uri": "spotify:track:4dbV37qzkwZOnkGVpsR0Q7"
                    }
                  ]
                }
              ],
              "page": 1,
              "psize": 3,
              "total_albums": 106
            }
        

## Album [/albums{?ids}]
<code>/album?ids={album_ids}/</code><br>
Request all information regarding specific albums related to **ids**

#### Parameters
- <code>album_ids</code> *(string, required)* - comma separated string of spotify ids for albums

+ Parameters
    + ids: `0nW0w37lrQ87k7PLZvC4qJ,1azUkThwd2HfUDdeNeT147,7kFmBZLF39JWv1OIRzWDkp` (string, required) - list of spotify ids for albums

### GET Album [GET]
+ Response 200 (application/json)
    + Attributes
        + artist_name: Cage The Elephant (string, required) - name of the artists
        + artists: [] (array, required) - array of artists and their information
        + col_img: {"url": "https://i.scdn.co/image/295f7e4e9cb73f559bbc14ee42097faaade17170"} (object, required) - contains url for img of album
        + db_id: 1 (number, required) - id in database
        + images: "https://i.scdn.co/image/a13016817c0496ee44a48adc80b5c345e8c8925e" (string, optional) - another way to find an image of the album
        + length: "38:17" (string, required) - total length of the album formatted in minutes and seconds
        + name: "Tell Me I'm Pretty" (string, required) - name of the album
        + num_tracks: 10 (number, required) - number of tracks in the album
        + release_date: `2015-12-18` (string, required) - date the album was released
        + spotify_uri: spotify:album:0nW0w37lrQ87k7PLZvC4qJ (string, required) - uri to find this artist on spotify
        + tracks: [] (array, required) - array of tracks on the album

    + Body
    
            {
              "albums": [
                {
                  "artist_name": "Cage The Elephant",
                  "artists": [
                    {
                      "col_img": {
                        "url": "https://i.scdn.co/image/295f7e4e9cb73f559bbc14ee42097faaade17170"
                      },
                      "db_id": 1,
                      "id": "26T3LtbuGT1Fu9m0eRq5X3",
                      "name": "Cage The Elephant",
                      "num_albums": 20,
                      "popularity": 76,
                      "recent_album": "Tell Me I'm Pretty",
                      "spotify_uri": "spotify:artist:26T3LtbuGT1Fu9m0eRq5X3",
                      "top_track": "Ain't No Rest for the Wicked"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/d1b4e53b2f815ab43fb140c439d0dcae27c16e8a"
                  },
                  "db_id": 1,
                  "id": "0nW0w37lrQ87k7PLZvC4qJ",
                  "images": "https://i.scdn.co/image/a13016817c0496ee44a48adc80b5c345e8c8925e",
                  "length": "38:17",
                  "name": "Tell Me I'm Pretty",
                  "num_tracks": 10,
                  "release_date": "2015-12-18",
                  "spotify_uri": "spotify:album:0nW0w37lrQ87k7PLZvC4qJ",
                  "tracks": [
                    {
                      "album": "Tell Me I'm Pretty",
                      "album_cover_url": "https://i.scdn.co/image/a13016817c0496ee44a48adc80b5c345e8c8925e",
                      "album_name": "Tell Me I'm Pretty",
                      "artist_name": "Cage The Elephant",
                      "artists": [
                        {
                          "artist_id": "26T3LtbuGT1Fu9m0eRq5X3",
                          "artist_name": "Cage The Elephant"
                        }
                      ]
                  ]
                },
                {
                  "artist_name": "Adele",
                  "artists": [
                    {
                      "col_img": {
                        "url": "https://i.scdn.co/image/cbbdfb209cc38b2999b1882f42ee642555316313"
                      },
                      "db_id": 2,
                      "id": "4dpARuHxo51G3z768sgnrY",
                      "name": "Adele",
                      "num_albums": 20,
                      "popularity": 91,
                      "recent_album": "21",
                      "spotify_uri": "spotify:artist:4dpARuHxo51G3z768sgnrY",
                      "top_track": "Hello"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/9cc65b0596960faa44a0328af13048573eefecb8"
                  },
                  "db_id": 2,
                  "id": "1azUkThwd2HfUDdeNeT147",
                  "images": "https://i.scdn.co/image/4e370e394e5b5ae0c4ab07fc0dcff31239c3da9c",
                  "length": "48:00",
                  "name": "21",
                  "num_tracks": 11,
                  "release_date": "2011-01-19",
                  "spotify_uri": "spotify:album:1azUkThwd2HfUDdeNeT147",
                  "tracks": [
                    {
                      "album": "21",
                      "album_cover_url": "https://i.scdn.co/image/4e370e394e5b5ae0c4ab07fc0dcff31239c3da9c",
                      "album_name": "21",
                      "artist_name": "Adele",
                      "artists": [
                        {
                          "artist_id": "4dpARuHxo51G3z768sgnrY",
                          "artist_name": "Adele"
                        }
                      ],
                      "col_img": {
                        "url": "https://i.scdn.co/image/9cc65b0596960faa44a0328af13048573eefecb8"
                      },
                      "db_id": 20,
                      "duration": "3:48",
                      "duration_ms": 228293,
                      "id": "1CkvWZme3pRgbzaxZnTl5X",
                      "name": "Rolling in the Deep",
                      "release_date": "2011-01-19",
                      "spotify_id": "1CkvWZme3pRgbzaxZnTl5X",
                      "spotify_uri": "spotify:track:1CkvWZme3pRgbzaxZnTl5X"
                    }
                  ]
                },
                {
                  "artist_name": "Lukas Graham",
                  "artists": [
                    {
                      "col_img": {
                        "url": "https://i.scdn.co/image/f4c6df387feebef2c94bde6117c38dd8dab69533"
                      },
                      "db_id": 3,
                      "id": "25u4wHJWxCA9vO0CzxAbK7",
                      "name": "Lukas Graham",
                      "num_albums": 20,
                      "popularity": 89,
                      "recent_album": "Lukas Graham (Blue Album)",
                      "spotify_uri": "spotify:artist:25u4wHJWxCA9vO0CzxAbK7",
                      "top_track": "7 Years"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/9df24b14adba7b4d9fd7de164390cca6bd97f9c8"
                  },
                  "db_id": 3,
                  "id": "7kFmBZLF39JWv1OIRzWDkp",
                  "images": "https://i.scdn.co/image/c5c91131c1725d05f4f26b3113799840c0de9255",
                  "length": "46:02",
                  "name": "Lukas Graham (Blue Album)",
                  "num_tracks": 14,
                  "release_date": "2015-10-30",
                  "spotify_uri": "spotify:album:7kFmBZLF39JWv1OIRzWDkp",
                  "tracks": [
                    {
                      "album": "Lukas Graham (Blue Album)",
                      "album_cover_url": "https://i.scdn.co/image/c5c91131c1725d05f4f26b3113799840c0de9255",
                      "album_name": "Lukas Graham (Blue Album)",
                      "artist_name": "Lukas Graham",
                      "artists": [
                        {
                          "artist_id": "25u4wHJWxCA9vO0CzxAbK7",
                          "artist_name": "Lukas Graham"
                        }
                      ],
                      "col_img": {
                        "url": "https://i.scdn.co/image/9df24b14adba7b4d9fd7de164390cca6bd97f9c8"
                      },
                      "db_id": 31,
                      "duration": "3:57",
                      "duration_ms": 237300,
                      "id": "4dbV37qzkwZOnkGVpsR0Q7",
                      "name": "7 Years",
                      "release_date": "2015-10-30",
                      "spotify_id": "4dbV37qzkwZOnkGVpsR0Q7",
                      "spotify_uri": "spotify:track:4dbV37qzkwZOnkGVpsR0Q7"
                    }
                  ]
                }
              ],
              "ids": [
                "0nW0w37lrQ87k7PLZvC4qJ",
                "1azUkThwd2HfUDdeNeT147",
                "7kFmBZLF39JWv1OIRzWDkp"
              ]
            }
        
# Group Tracks
## Arbitrary Tracks [/tracks/{page_num}{?psize,sort,order}]
<code>/tracks/{page_num}?psize={psize}&sort={col_attr}&order={asc_desc}</code><br>
Request an arbitrary list of albums. You can specify the number of tracks returned, using the page and optional psize as offset. <br>
Optionally you can set to sort by a specific column attribute and determine if the order is ascending or descending.
#### Parameters
- <code>page_num</code> *(number, required)* - used as an offset to query by page
- <code>psize</code> *(number, optional)* - used to specify the size of the list
- <code>col_attr</code> *(string, optional)* - takes a specific column to sort the list of tracks by
- <code>asc_desc</code> *(string, optional)* - default ascending sort order when sort is set, can set to descending with 'desc'

#### Sort options
- <code>track_title</code>
- <code>artist_name</code>
- <code>release_date</code>
- <code>album_name</code>
- <code>duration</code>

+ Parameters
    + page_num: 1 (number, required) - indicates the offset or page
    + psize: 3 (number, optional) - indicates the number of tracks per page
    + sort: duration (string, optional) - takes a specific column to sort the list of tracks by
    + order: desc (string, optional) - default ascending sort order when sort is set, can set to descending with 'desc'

### GET Arbitrary Tracks [GET]
+ Response 200 (application/json)
    + Attributes
        + album: "Cage The Elephant" (string, required) - name of the album the track is in
        + album_cover_url: https://i.scdn.co/image/093f43760cd933c671cc2a6dd457ccdfc5f71373 (string, required) - url to the album cover
        + album_name: "Cage The Elephant" (string, required) - name of the album
        + artist_name: "Cage The Elephant" (string, required) - name of the artist
        + artists: [] (array, required) - array of artists involved and their info
        + col_img: {"url": "https://i.scdn.co/image/d4d346d1e17c5f9661cf0a76cf790b9f070c7f34"} (object, required) - href to the album cover
        + db_id: 1 (number, required) - database id
        + duration: "2:55" (string, required) - duration of track in minutes and seconds format
        + id: "3kb72STxc2959ZqsTwu52i" (string, required) - spotify id for the track
        + name: "Ain't No Rest for the Wicked" (string, required) - name of the specific track
        + release_date: `2009-04-20` (string, required) - release date of the album/track
        + spotify_id: "3kb72STxc2959ZqsTwu52i" (string, required) - spotify id for the track
        + spotify_uri: "spotify:track:3kb72STxc2959ZqsTwu52i" (string, required) - uri of the track on spotify
        
    + Body
    
            {
              "page": 1,
              "psize": 3,
              "total_count": 283,
              "tracks": [
                {
                  "album": "Cage The Elephant",
                  "album_cover_url": "https://i.scdn.co/image/093f43760cd933c671cc2a6dd457ccdfc5f71373",
                  "album_name": "Cage The Elephant",
                  "artist_name": "Cage The Elephant",
                  "artists": [
                    {
                      "artist_id": "26T3LtbuGT1Fu9m0eRq5X3",
                      "artist_name": "Cage The Elephant"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/d4d346d1e17c5f9661cf0a76cf790b9f070c7f34"
                  },
                  "db_id": 1,
                  "duration": "2:55",
                  "duration_ms": 175493,
                  "id": "3kb72STxc2959ZqsTwu52i",
                  "name": "Ain't No Rest for the Wicked",
                  "release_date": "2009-04-20",
                  "spotify_id": "3kb72STxc2959ZqsTwu52i",
                  "spotify_uri": "spotify:track:3kb72STxc2959ZqsTwu52i"
                },
                {
                  "album": "Hello",
                  "album_cover_url": "https://i.scdn.co/image/f71517e8919892273de8d8677e42cdcf1b976aa7",
                  "album_name": "Hello",
                  "artist_name": "Adele",
                  "artists": [
                    {
                      "artist_id": "4dpARuHxo51G3z768sgnrY",
                      "artist_name": "Adele"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/220fe5804f244f41aa216c4e3de17eafbf552341"
                  },
                  "db_id": 2,
                  "duration": "4:55",
                  "duration_ms": 295493,
                  "id": "0ENSn4fwAbCGeFGVUbXEU3",
                  "name": "Hello",
                  "release_date": "2015-10-23",
                  "spotify_id": "0ENSn4fwAbCGeFGVUbXEU3",
                  "spotify_uri": "spotify:track:0ENSn4fwAbCGeFGVUbXEU3"
                },
                {
                  "album": "7 Years",
                  "album_cover_url": "https://i.scdn.co/image/6eaeb0e59e50269f879d7e643ec0c4b5c16cb6bf",
                  "album_name": "7 Years",
                  "artist_name": "Lukas Graham",
                  "artists": [
                    {
                      "artist_id": "25u4wHJWxCA9vO0CzxAbK7",
                      "artist_name": "Lukas Graham"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/8eea6a88415940dbe2eff2a6275d6a4a3407eeee"
                  },
                  "db_id": 3,
                  "duration": "3:57",
                  "duration_ms": 237300,
                  "id": "2vDT1uU6hZgdp3PbWGr0Xy",
                  "name": "7 Years",
                  "release_date": "2015-10-22",
                  "spotify_id": "2vDT1uU6hZgdp3PbWGr0Xy",
                  "spotify_uri": "spotify:track:2vDT1uU6hZgdp3PbWGr0Xy"
                }
              ]
            }

## Specific Tracks [/tracks{?ids}]
<code>/tracks?ids={track_ids}</code><br>
Request all information regarding specific tracks related to **ids**
#### Parameters
- <code>track_ids</code> *(string, required)* - comma separated string of spotify ids for tracks

+ Parameters
    + ids: `3kb72STxc2959ZqsTwu52i,0ENSn4fwAbCGeFGVUbXEU3,2vDT1uU6hZgdp3PbWGr0Xy` (number, required) - list of spotify ids for tracks

### GET Specific Tracks [GET]
+ Response 200 (application/json)
    + Attributes
        + album: `Hello` (string, required) - album associated with track
        + album_cover_url: "https://i.scdn.co/image/f71517e8919892273de8d8677e42cdcf1b976aa7" (string, required) - url to the album cover
        + album_name: `Hello` (string, required) - name of album
        + artist_name: `Adele` (string, required) - name of the artist
        + artists: [] (array, required) - array of artists involved and their info
        + col_img: {"url": "https://i.scdn.co/image/220fe5804f244f41aa216c4e3de17eafbf552341"} (object, required) - url to img for the track
        + db_id: 2 (number, required) - database id
        + duration: `4:55` (string, required) - the duration of the track formatted in minutes and seconds
        + duration_ms: 295493 (number, required) - the duration of the track in milliseconds
        + id: `0ENSn4fwAbCGeFGVUbXEU3` (string, required) - the spotify id of the track
        + name: `Hello` (string, required) - the name of the track
        + release_date: `2015-10-23` (string, required) - the release date of the track
        + spotify_id: `0ENSn4fwAbCGeFGVUbXEU3` (string, required) - the spotify id of the track
        + spotify_uri: `spotify:track:0ENSn4fwAbCGeFGVUbXEU3` (string, required) - the uri of the track on spotify

    + Body
    
            {
              "ids": [
                "3kb72STxc2959ZqsTwu52i",
                "0ENSn4fwAbCGeFGVUbXEU3",
                "2vDT1uU6hZgdp3PbWGr0Xy"
              ],
              "tracks": [
                {
                  "album": "Cage The Elephant",
                  "album_cover_url": "https://i.scdn.co/image/093f43760cd933c671cc2a6dd457ccdfc5f71373",
                  "album_name": "Cage The Elephant",
                  "artist_name": "Cage The Elephant",
                  "artists": [
                    {
                      "artist_id": "26T3LtbuGT1Fu9m0eRq5X3",
                      "artist_name": "Cage The Elephant"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/d4d346d1e17c5f9661cf0a76cf790b9f070c7f34"
                  },
                  "db_id": 1,
                  "duration": "2:55",
                  "duration_ms": 175493,
                  "id": "3kb72STxc2959ZqsTwu52i",
                  "name": "Ain't No Rest for the Wicked",
                  "release_date": "2009-04-20",
                  "spotify_id": "3kb72STxc2959ZqsTwu52i",
                  "spotify_uri": "spotify:track:3kb72STxc2959ZqsTwu52i"
                },
                {
                  "album": "Hello",
                  "album_cover_url": "https://i.scdn.co/image/f71517e8919892273de8d8677e42cdcf1b976aa7",
                  "album_name": "Hello",
                  "artist_name": "Adele",
                  "artists": [
                    {
                      "artist_id": "4dpARuHxo51G3z768sgnrY",
                      "artist_name": "Adele"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/220fe5804f244f41aa216c4e3de17eafbf552341"
                  },
                  "db_id": 2,
                  "duration": "4:55",
                  "duration_ms": 295493,
                  "id": "0ENSn4fwAbCGeFGVUbXEU3",
                  "name": "Hello",
                  "release_date": "2015-10-23",
                  "spotify_id": "0ENSn4fwAbCGeFGVUbXEU3",
                  "spotify_uri": "spotify:track:0ENSn4fwAbCGeFGVUbXEU3"
                },
                {
                  "album": "7 Years",
                  "album_cover_url": "https://i.scdn.co/image/6eaeb0e59e50269f879d7e643ec0c4b5c16cb6bf",
                  "album_name": "7 Years",
                  "artist_name": "Lukas Graham",
                  "artists": [
                    {
                      "artist_id": "25u4wHJWxCA9vO0CzxAbK7",
                      "artist_name": "Lukas Graham"
                    }
                  ],
                  "col_img": {
                    "url": "https://i.scdn.co/image/8eea6a88415940dbe2eff2a6275d6a4a3407eeee"
                  },
                  "db_id": 3,
                  "duration": "3:57",
                  "duration_ms": 237300,
                  "id": "2vDT1uU6hZgdp3PbWGr0Xy",
                  "name": "7 Years",
                  "release_date": "2015-10-22",
                  "spotify_id": "2vDT1uU6hZgdp3PbWGr0Xy",
                  "spotify_uri": "spotify:track:2vDT1uU6hZgdp3PbWGr0Xy"
                }
              ]
            }

# Group Static Content <DEPRECATED>
**DEPRECATED: Please use the routes above**<br>
This section was used in Part 1 of the Project using known id's for specific Artists, Albums and Tracks<br>
Use Production Server to see Spotify's response and data structures for each request.

## Spotify Artists [/get_artists/{page_num}]
<code>/get_artists/{page_num}</code><br>
<strike>Uses request to Spotify's Web API to pull information about three specific artists</strike><br>
This now calls `artists/{page_num}` and returns the top 20 artists from the database

+ Parameters
    + page_num: 1 (number, required) - indicates the offset or page

### GET Artists [GET]
+ Response 200 (application/json)

## Spotify Albums [/get_albums/{page_num}]
<code>/get_albums/{page_num}</code><br>
<strike>Uses request to Spotify's Web API to pull information about three specific albums</strike><br>
This now calls `albums/{page_num}` and returns the top 20 albums from the database

+ Parameters
    + page_num: 1 (number, required) - indicates the offset or page

### GET Albums [GET]
+ Response 200 (application/json)

## Spotify Tracks [/get_tracks/{page_num}]
<code>/get_tracks/{page_num}</code><br>
<strike>Uses request to Spotify's Web API to pull information about three specific tracks</strike><br>
This now calls `tracks/{page_num}` and returns the top 20 tracks from the database

+ Parameters
    + page_num: 1 (number, required) - indicates the offset or page

### GET Tracks [GET]
+ Response 200 (application/json)
